package com.travelblogger.entities;
// Generated Jul 2, 2020 11:36:25 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblAccount generated by hbm2java
 */
@Entity
@Table(name = "tbl_account", catalog = "travelblogger")
public class TblAccount implements java.io.Serializable {

	private Integer idAccount;
	private TblRole tblRole;
	private String username;
	private String email;
	private String phoneNumber;
	private String password;
	private String salt;
	private String aliases;
	private int activeFlag;
	private Set<TblCommentPost> tblCommentPosts = new HashSet<TblCommentPost>(0);
	private Set<TblSavePost> tblSavePosts = new HashSet<TblSavePost>(0);
	private Set<TblLikePost> tblLikePosts = new HashSet<TblLikePost>(0);

	public TblAccount() {
	}

	public TblAccount(TblRole tblRole, String username, String email, String phoneNumber, String password, String salt,
			String aliases, int activeFlag) {
		this.tblRole = tblRole;
		this.username = username;
		this.email = email;
		this.phoneNumber = phoneNumber;
		this.password = password;
		this.salt = salt;
		this.aliases = aliases;
		this.activeFlag = activeFlag;
	}

	public TblAccount(TblRole tblRole, String username, String email, String phoneNumber, String password, String salt,
			String aliases, int activeFlag, Set<TblCommentPost> tblCommentPosts, Set<TblSavePost> tblSavePosts,
			Set<TblLikePost> tblLikePosts) {
		this.tblRole = tblRole;
		this.username = username;
		this.email = email;
		this.phoneNumber = phoneNumber;
		this.password = password;
		this.salt = salt;
		this.aliases = aliases;
		this.activeFlag = activeFlag;
		this.tblCommentPosts = tblCommentPosts;
		this.tblSavePosts = tblSavePosts;
		this.tblLikePosts = tblLikePosts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_account", unique = true, nullable = false)
	public Integer getIdAccount() {
		return this.idAccount;
	}

	public void setIdAccount(Integer idAccount) {
		this.idAccount = idAccount;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role", nullable = false)
	public TblRole getTblRole() {
		return this.tblRole;
	}

	public void setTblRole(TblRole tblRole) {
		this.tblRole = tblRole;
	}

	@Column(name = "username", nullable = false, length = 100)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone_number", nullable = false, length = 50)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "password", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "salt", nullable = false, length = 50)
	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	@Column(name = "aliases", nullable = false, length = 100)
	public String getAliases() {
		return this.aliases;
	}

	public void setAliases(String aliases) {
		this.aliases = aliases;
	}

	@Column(name = "active_flag", nullable = false)
	public int getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(int activeFlag) {
		this.activeFlag = activeFlag;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblAccount")
	public Set<TblCommentPost> getTblCommentPosts() {
		return this.tblCommentPosts;
	}

	public void setTblCommentPosts(Set<TblCommentPost> tblCommentPosts) {
		this.tblCommentPosts = tblCommentPosts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblAccount")
	public Set<TblSavePost> getTblSavePosts() {
		return this.tblSavePosts;
	}

	public void setTblSavePosts(Set<TblSavePost> tblSavePosts) {
		this.tblSavePosts = tblSavePosts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblAccount")
	public Set<TblLikePost> getTblLikePosts() {
		return this.tblLikePosts;
	}

	public void setTblLikePosts(Set<TblLikePost> tblLikePosts) {
		this.tblLikePosts = tblLikePosts;
	}

}
