package com.travelblogger.entities;
// Generated Jul 2, 2020 11:36:25 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblSavePost generated by hbm2java
 */
@Entity
@Table(name = "tbl_save_post", catalog = "travelblogger")
public class TblSavePost implements java.io.Serializable {

	private Integer idSavePost;
	private TblAccount tblAccount;
	private TblPost tblPost;
	private Date saveDate;
	private Integer activeFlag;

	public TblSavePost() {
	}

	public TblSavePost(TblAccount tblAccount, TblPost tblPost, Date saveDate) {
		this.tblAccount = tblAccount;
		this.tblPost = tblPost;
		this.saveDate = saveDate;
	}

	public TblSavePost(TblAccount tblAccount, TblPost tblPost, Date saveDate, Integer activeFlag) {
		this.tblAccount = tblAccount;
		this.tblPost = tblPost;
		this.saveDate = saveDate;
		this.activeFlag = activeFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_save_post", unique = true, nullable = false)
	public Integer getIdSavePost() {
		return this.idSavePost;
	}

	public void setIdSavePost(Integer idSavePost) {
		this.idSavePost = idSavePost;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_account", nullable = false)
	public TblAccount getTblAccount() {
		return this.tblAccount;
	}

	public void setTblAccount(TblAccount tblAccount) {
		this.tblAccount = tblAccount;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_post", nullable = false)
	public TblPost getTblPost() {
		return this.tblPost;
	}

	public void setTblPost(TblPost tblPost) {
		this.tblPost = tblPost;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "save_date", nullable = false, length = 10)
	public Date getSaveDate() {
		return this.saveDate;
	}

	public void setSaveDate(Date saveDate) {
		this.saveDate = saveDate;
	}

	@Column(name = "active_flag")
	public Integer getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(Integer activeFlag) {
		this.activeFlag = activeFlag;
	}

}
