package com.travelblogger.entities;
// Generated Jul 2, 2020 11:38:06 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * TblCommentPost generated by hbm2java
 */
@Entity
@Table(name = "tbl_comment_post", catalog = "travelblogger")
public class TblCommentPost implements java.io.Serializable {

	private Integer idCommentPost;
	private int idAccount;
	private int idPost;
	private String comment;
	private int activeFlag;

	public TblCommentPost() {
	}

	public TblCommentPost(int idAccount, int idPost, String comment, int activeFlag) {
		this.idAccount = idAccount;
		this.idPost = idPost;
		this.comment = comment;
		this.activeFlag = activeFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_comment_post", unique = true, nullable = false)
	public Integer getIdCommentPost() {
		return this.idCommentPost;
	}

	public void setIdCommentPost(Integer idCommentPost) {
		this.idCommentPost = idCommentPost;
	}

	@Column(name = "id_account", nullable = false)
	public int getTblAccount() {
		return this.idAccount;
	}

	public void setTblAccount(int idAccount) {
		this.idAccount = idAccount;
	}

	@JoinColumn(name = "id_post", nullable = false)
	public int getTblPost() {
		return this.idPost;
	}

	public void setTblPost(int idPost) {
		this.idPost = idPost;
	}

	@Column(name = "comment", nullable = false, length = 65535)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "active_flag", nullable = false)
	public int getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(int activeFlag) {
		this.activeFlag = activeFlag;
	}

}
