package com.travelblogger.entities;
// Generated Jul 2, 2020 11:38:06 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * TblCommentPost generated by hbm2java
 */
@Entity
@Table(name = "tbl_comment_post", catalog = "travelblogger")
public class TblCommentPost implements java.io.Serializable {

	private Integer idCommentPost;
	private TblAccount tblAccount;
	private TblPost tblPost;
	private String comment;
	private int activeFlag;

	public TblCommentPost() {
	}

	public TblCommentPost(TblAccount tblAccount, TblPost tblPost, String comment, int activeFlag) {
		this.tblAccount = tblAccount;
		this.tblPost = tblPost;
		this.comment = comment;
		this.activeFlag = activeFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_comment_post", unique = true, nullable = false)
	public Integer getIdCommentPost() {
		return this.idCommentPost;
	}

	public void setIdCommentPost(Integer idCommentPost) {
		this.idCommentPost = idCommentPost;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_account", nullable = false)
	public TblAccount getTblAccount() {
		return this.tblAccount;
	}

	public void setTblAccount(TblAccount tblAccount) {
		this.tblAccount = tblAccount;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_post", nullable = false)
	public TblPost getTblPost() {
		return this.tblPost;
	}

	public void setTblPost(TblPost tblPost) {
		this.tblPost = tblPost;
	}

	@Column(name = "comment", nullable = false, length = 65535)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "active_flag", nullable = false)
	public int getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(int activeFlag) {
		this.activeFlag = activeFlag;
	}

}
