package com.travelblogger.entities;
// Generated Jul 2, 2020 11:38:06 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * TblLikePost generated by hbm2java
 */
@Entity
@Table(name = "tbl_like_post", catalog = "travelblogger")
public class TblLikePost implements java.io.Serializable {

	private Integer idLikePost;
	private TblAccount tblAccount;
	private TblPost tblPost;
	private Integer activeFlag;

	public TblLikePost() {
	}

	public TblLikePost(TblAccount tblAccount, TblPost tblPost) {
		this.tblAccount = tblAccount;
		this.tblPost = tblPost;
	}

	public TblLikePost(TblAccount tblAccount, TblPost tblPost, Integer activeFlag) {
		this.tblAccount = tblAccount;
		this.tblPost = tblPost;
		this.activeFlag = activeFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_like_post", unique = true, nullable = false)
	public Integer getIdLikePost() {
		return this.idLikePost;
	}

	public void setIdLikePost(Integer idLikePost) {
		this.idLikePost = idLikePost;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_account", nullable = false)
	public TblAccount getTblAccount() {
		return this.tblAccount;
	}

	public void setTblAccount(TblAccount tblAccount) {
		this.tblAccount = tblAccount;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_post", nullable = false)
	public TblPost getTblPost() {
		return this.tblPost;
	}

	public void setTblPost(TblPost tblPost) {
		this.tblPost = tblPost;
	}

	@Column(name = "active_flag")
	public Integer getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(Integer activeFlag) {
		this.activeFlag = activeFlag;
	}

}
