package com.travelblogger.entities;
// Generated Jul 2, 2020 11:38:06 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * TblLikePost generated by hbm2java
 */
@Entity
@Table(name = "tbl_like_post", catalog = "travelblogger")
public class TblLikePost implements java.io.Serializable {

	private Integer idLikePost;
	private int idAccount;
	private int idPost;
	private Integer activeFlag;

	public TblLikePost() {
	}

	public TblLikePost(int idAccount, int idPost) {
		this.idAccount = idAccount;
		this.idPost = idPost;
	}

	public TblLikePost(int idAccount, int idPost, Integer activeFlag) {
		this.idAccount = idAccount;
		this.idPost = idPost;
		this.activeFlag = activeFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_like_post", unique = true, nullable = false)
	public Integer getIdLikePost() {
		return this.idLikePost;
	}

	public void setIdLikePost(Integer idLikePost) {
		this.idLikePost = idLikePost;
	}

	@Column(name = "id_account", nullable = false)
	public int getTblAccount() {
		return this.idAccount;
	}

	public void setTblAccount(int idAccount) {
		this.idAccount = idAccount;
	}

	@Column(name = "id_post", nullable = false)
	public int getTblPost() {
		return this.idPost;
	}

	public void setTblPost(int idPost) {
		this.idPost = idPost;
	}

	@Column(name = "active_flag")
	public Integer getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(Integer activeFlag) {
		this.activeFlag = activeFlag;
	}

}
