package com.travelblogger.entities;
// Generated Jul 2, 2020 11:38:06 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * TblRole generated by hbm2java
 */
@Entity
@Table(name = "tbl_role", catalog = "travelblogger")
public class TblRole implements java.io.Serializable {

	private int idRole;
	private String nameRole;
	private int activeFlag;
//	private Set<TblAccount> tblAccounts = new HashSet<TblAccount>(0);

	public TblRole() {
	}

	public TblRole(int idRole, String nameRole, int activeFlag) {
		this.idRole = idRole;
		this.nameRole = nameRole;
		this.activeFlag = activeFlag;
	}

//	public TblRole(int idRole, String nameRole, int activeFlag) {
//		this.idRole = idRole;
//		this.nameRole = nameRole;
//		this.activeFlag = activeFlag;
////		this.tblAccounts = tblAccounts;
//	}

	@Id

	@Column(name = "id_role", unique = true, nullable = false)
	public int getIdRole() {
		return this.idRole;
	}

	public void setIdRole(int idRole) {
		this.idRole = idRole;
	}

	@Column(name = "name_role", nullable = false)
	public String getNameRole() {
		return this.nameRole;
	}

	public void setNameRole(String nameRole) {
		this.nameRole = nameRole;
	}

	@Column(name = "active_flag", nullable = false)
	public int getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(int activeFlag) {
		this.activeFlag = activeFlag;
	}

//	@Column(fetch = FetchType.LAZY, mappedBy = "tblRole")
//	public Set<TblAccount> getTblAccounts() {
//		return this.tblAccounts;
//	}
//
//	public void setTblAccounts(Set<TblAccount> tblAccounts) {
//		this.tblAccounts = tblAccounts;
//	}

}
