package com.travelblogger.entities;
// Generated Jul 2, 2020 11:38:06 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * TblSavePost generated by hbm2java
 */
@Entity
@Table(name = "tbl_save_post", catalog = "travelblogger")
public class TblSavePost implements java.io.Serializable {

	private Integer idSavePost;
	private int idAccount;
	private int idPost;
	private Date saveDate;
	private Integer activeFlag;

	public TblSavePost() {
	}

	public TblSavePost(int tblAccount, int tblPost, Date saveDate) {
		this.idAccount = idAccount;
		this.idPost = idPost;
		this.saveDate = saveDate;
	}

	public TblSavePost(int idAccount, int idPost, Date saveDate, Integer activeFlag) {
		this.idAccount = idAccount;
		this.idPost = idPost;
		this.saveDate = saveDate;
		this.activeFlag = activeFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_save_post", unique = true, nullable = false)
	public Integer getIdSavePost() {
		return this.idSavePost;
	}

	public void setIdSavePost(Integer idSavePost) {
		this.idSavePost = idSavePost;
	}

	@Column(name = "id_account", nullable = false)
	public int getTblAccount() {
		return this.idAccount;
	}

	public void setTblAccount(int idAccount) {
		this.idAccount = idAccount;
	}

	@Column(name = "id_post", nullable = false)
	public int getTblPost() {
		return this.idPost;
	}

	public void setTblPost(int idPost) {
		this.idPost = idPost;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "save_date", nullable = false, length = 10)
	public Date getSaveDate() {
		return this.saveDate;
	}

	public void setSaveDate(Date saveDate) {
		this.saveDate = saveDate;
	}

	@Column(name = "active_flag")
	public Integer getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(Integer activeFlag) {
		this.activeFlag = activeFlag;
	}

}
