package com.travelblogger.entities;
// Generated Jul 2, 2020 11:38:06 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblTopics generated by hbm2java
 */
@Entity
@Table(name = "tbl_topics", catalog = "travelblogger")
public class TblTopics implements java.io.Serializable {

	private int idTopic;
	private String nameTopic;
	private int activeFlag;

	public TblTopics() {
	}

	public TblTopics(int idTopic, String nameTopic, int activeFlag) {
		this.idTopic = idTopic;
		this.nameTopic = nameTopic;
		this.activeFlag = activeFlag;
	}

//	public TblTopics(int idTopic, String nameTopic, int activeFlag, Set<TblPost> tblPosts) {
//		this.idTopic = idTopic;
//		this.nameTopic = nameTopic;
//		this.activeFlag = activeFlag;
//	}

	@Id

	@Column(name = "id_topic", unique = true, nullable = false)
	public int getIdTopic() {
		return this.idTopic;
	}

	public void setIdTopic(int idTopic) {
		this.idTopic = idTopic;
	}

	@Column(name = "name_topic", nullable = false)
	public String getNameTopic() {
		return this.nameTopic;
	}

	public void setNameTopic(String nameTopic) {
		this.nameTopic = nameTopic;
	}

	@Column(name = "active_flag", nullable = false)
	public int getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(int activeFlag) {
		this.activeFlag = activeFlag;
	}
}
